os: linux
dist: xenial
cache:
  directories:
  - $HOME/buildout-cache
language: python
python:
  - 2.7
  - 3.8
env:
  - PLONE=4.3
  - PLONE=5.0
  - PLONE=5.1
  - PLONE=5.2
jobs:
  exclude:
  - python: 3.8
    env: PLONE=4.3
  - python: 3.8
    env: PLONE=5.0
  - python: 3.8
    env: PLONE=5.1
# With plone 5.0 https://dist.plone.org/release/5.0-latest/versions.cfg
# requires pycodestyle = 2.3.1 and also flake8>=2.4.0 but flake8 >=2.6.0
# breaks pycodestle 2.3.1. So for plone 5.0 we need to pin to flake8 2.5.5
before_install:
  - if [ $PLONE == "5.0" ]; then
    printf "\n[versions]\nflake8 = 2.5.5" >> code-analysis.cfg;
    fi
install:
  - sed -ie "s#test-4.x.cfg#test-$PLONE.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N
script: bin/code-analysis && bin/test
after_success:
# XXX: https://github.com/urllib3/urllib3/issues/1456
- pip install urllib3==1.23
- pip install coverage
- coverage run bin/test
- pip install coveralls
- coveralls